import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { ThemeProvider } from 'next-themes';
import '@/styles/globals.css';
import { notFound } from 'next/navigation';
import { NavbarMenu } from '@/components/atasui/navbar';

export const metadata = {
  title: 'Atas Starter Kit',
  description: 'Generated by ATAS TECH'
};

const rtlLocales = ['ar'];

async function getMessages(locale: string) {
  try {
    const messages = (await import(`../../messages/${locale}.json`)).default;
    return messages;
  } catch (error) {
    notFound();
  }
}

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages(locale);

  if (!messages) {
    notFound();
  }

  return (
    <html lang={locale} dir={rtlLocales.includes(locale) ? 'rtl' : 'ltr'}>
      <body className={`${GeistSans.variable} ${GeistMono.variable} ${rtlLocales.includes(locale) ? 'rtl' : ''}`}>
        <ThemeProvider attribute="class">
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NavbarMenu />
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
